services:
  auth:
    url: http://localhost:8090 # 인증 서비스 URL
  post:
    url: http://localhost:8093  # 게시글 서비스 URL
  chat:
    url: http://localhost:8095  # 채팅 서비스 URL
  noti:
    url: http://localhost:8097  # 알림 서비스 URL
  payment:
    url: http://localhost:8100 # 결제 서비스 URL
  search:
    url: http://localhost:8103 # 검색 서비스 URL
  carecenter:
    url: http://localhost:8105 # 병원 서비스 URL