custom:
  jwt:
    secretKey: E0MLNdqEml-egCwX5gRY2AL4LMyFpzaf740tHLIIErA=
  accessToken:
    expirationSeconds: "#{60*15}
services:
  auth:
    url: http://110.165.16.61:8090  # 인증 서비스 URL
  post:
    url: http://110.165.16.61:8093  # 인증 서비스 URL
  chat:
    url: http://110.165.16.61:8095  # 채팅 서비스 URL
  noti:
    url: http://110.165.16.61:8097  # 인증 서비스 URL
