services:
  auth:
    url: http://110.165.16.61:8090  # 인증 서비스 URL
#    url: http://localhost:8091  # 인증 서비스 URL
  noti:
    url: http://110.165.16.61:8097  # 인증 서비스 URL
  post:
    url: http://110.165.16.61:8093  # 인증 서비스 URL