services:
  auth:
#    url: http://43.203.126.129:8092  # 인증 서비스 URL
#    url: http://localhost:8091  # 인증 서비스 URL
    url: http://172.17.0.1:8091
  noti:
#    url: http://43.203.126.129:8094  # 인증 서비스 URL
    url: http://172.17.0.1:8094