services:
  auth:
    url: http://localhost:8090 # 인증 서비스 URL
#    url: http://localhost:8091  # 인증 서비스 URL
  noti:
    url: http://localhost:8097  # 인증 서비스 URL
  post:
    url: http://localhost:8093  # 인증 서비스 URL